# All the dts files for Freescale (now NXP) systems we support.
DTS=	freescale/fsl-ls1012a-frdm.dts \
	freescale/fsl-ls1012a-frwy.dts \
	freescale/fsl-ls1012a-oxalis.dts \
	freescale/fsl-ls1012a-qds.dts \
	freescale/fsl-ls1012a-rdb.dts \
	freescale/fsl-ls1028a-kontron-kbox-a-230-ls.dts \
	freescale/fsl-ls1028a-kontron-sl28.dts \
	freescale/fsl-ls1028a-kontron-sl28-var1.dts \
	freescale/fsl-ls1028a-kontron-sl28-var2.dts \
	freescale/fsl-ls1028a-kontron-sl28-var3-ads2.dts \
	freescale/fsl-ls1028a-kontron-sl28-var4.dts \
	freescale/fsl-ls1028a-qds-13bb.dts \
	freescale/fsl-ls1028a-qds-65bb.dts \
	freescale/fsl-ls1028a-qds-7777.dts \
	freescale/fsl-ls1028a-qds-85bb.dts \
	freescale/fsl-ls1028a-qds-899b.dts \
	freescale/fsl-ls1028a-qds-9999.dts \
	freescale/fsl-ls1028a-qds.dts \
	freescale/fsl-ls1028a-rdb.dts \
	freescale/fsl-ls1043a-qds.dts \
	freescale/fsl-ls1043a-rdb.dts \
	freescale/fsl-ls1046a-frwy.dts \
	freescale/fsl-ls1046a-qds.dts \
	freescale/fsl-ls1046a-rdb.dts \
	freescale/fsl-ls1088a-qds.dts \
	freescale/fsl-ls1088a-rdb.dts \
	freescale/fsl-ls1088a-ten64.dts \
	freescale/fsl-ls2080a-qds.dts \
	freescale/fsl-ls2080a-rdb.dts \
	freescale/fsl-ls2080a-simu.dts \
	freescale/fsl-ls2081a-rdb.dts \
	freescale/fsl-ls2088a-qds.dts \
	freescale/fsl-ls2088a-rdb.dts \
	freescale/fsl-lx2160a-bluebox3.dts \
	freescale/fsl-lx2160a-bluebox3-rev-a.dts \
	freescale/fsl-lx2160a-clearfog-cx.dts \
	freescale/fsl-lx2160a-honeycomb.dts \
	freescale/fsl-lx2160a-qds.dts \
	freescale/fsl-lx2160a-rdb.dts \
	freescale/fsl-lx2162a-qds.dts \
	freescale/mono-gateway-dk.dts

.include <bsd.dtb.mk>
